[package]
name = "libcart"
version = "0.1.0"
authors = ["Josh Lindsey <Joshua.Lindsey@georgetown.edu>"]
publish = false

[lib]
crate-type = ["rlib"]

[profile.release]
lto = true
panic = "abort"

[workspace]

[dependencies]
crypto = { path = "crypto" }
server = { path = "server" }
log = "0.3"

